name: Upload SPA Assets
author: Guild Education
description: Uploads SPA assets to
inputs:
  aws-access-key-id:
    description: 'AWS access key id for API access'
    required: true
  aws-secret-access-key:
    description: 'AWS secret access key for API access'
    required: true
  aws_region:
    description: 'AWS region'
    default: 'us-west-2'
  dist:
    description: 'Path to the SPA artifacts'
    default: 'public'
  env:
    description: 'The deployment environment'
    required: true
runs:
  using: 'node20'
  main: 'index.js'
