name: Cleanup PR Application

on:
  pull_request:
    types: [closed]

jobs:
  cleanup_pull_request:
    runs-on: ubuntu-20.04
    container: node:18
    name: Cleanup PR App in AWS
    env:
      NPM_TOKEN: ${{ secrets.DEVOPS_ALL_NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: yarn install
        run: yarn --frozen-lockfile --network-timeout 120000

      - name: Cleanup PR App
        uses: ./.github/actions/pull-request-cleanup
        with:
          aws-access-key-id: ${{ secrets.DEVOPS_DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEVOPS_DEV_AWS_SECRET_ACCESS_KEY }}
